CREATE TABLE `mip_message_checks` (
	`id` varchar(36) NOT NULL,
	`user_id` varchar(36) NOT NULL,
	`session_id` varchar(36),
	`device_id` varchar(36),
	`channel` enum('sms','whatsapp','line','telegram','kakaotalk','instagram','rcs','other') NOT NULL,
	`sender_number` varchar(50),
	`sender_name` varchar(100),
	`message_content` text NOT NULL,
	`message_url` text,
	`risk_score` int NOT NULL,
	`verdict` enum('safe','suspicious','phishing','blocked') NOT NULL,
	`verdict_reason` text,
	`sender_trust_score` int DEFAULT 0,
	`urgency_score` int DEFAULT 0,
	`threat_score` int DEFAULT 0,
	`link_risk_score` int DEFAULT 0,
	`impersonation_score` int DEFAULT 0,
	`info_request_score` int DEFAULT 0,
	`user_action` enum('pending','approved','rejected','auto_blocked') NOT NULL DEFAULT 'pending',
	`user_action_at` bigint,
	`checked_at` bigint NOT NULL,
	`created_at` bigint NOT NULL,
	CONSTRAINT `mip_message_checks_id` PRIMARY KEY(`id`)
);
